### ISSUE TITLE
当日のTODOを確認する方法を考える

### ISSUE THREAD

**Issue by yanac** [covelline/mountain#11]
## TODO
- [x] 当日のTODOを確認する方法を考えるissueを作る @yanac 
	- 登る前に軽くラジオ体操する
	- 舗装された道路でも休憩を入れる
	- min / km を測ってみる

**Comment by takkumattsu** [comment]
## 案
リーダーがカレンダーに入れて出発時刻に通知されるようにする

**Comment by takkumattsu** [comment]
@yanac 代案なさそうだしこれ今回試してみる！
