### ISSUE TITLE
風除け(風防)について

### ISSUE THREAD

**Issue by TakkuMattsu** [covelline/mountain#4]
## 概要

[振り返り](https://covelline.staging.facilio.team/documents/373)より

- 風防(風除け)
  - [バーゴ アルミニウム ウインドスクリーン ナチュラルT-420](https://www.amazon.co.jp/dp/B007S3OQW0)
    - コンパクト
    - サイズ感もちょうどいいと思う
    - ![image](https://user-images.githubusercontent.com/3356758/56301189-46975680-6172-11e9-8b5b-113dd1c88ae1.png)
    - ![image](https://user-images.githubusercontent.com/3356758/56301238-60389e00-6172-11e9-8ad8-9d24728a62db.png)
    - 風防にしては高い...
  - その他
    - [アマゾンで検索するともうちょっと安いのもある](https://www.amazon.co.jp/s?k=%E3%82%A6%E3%82%A3%E3%83%B3%E3%83%89%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3)
    - 背が高いやつは地面にさせれば安定するけど、机の上とかだと安定感ないかも？

**Comment by TakkuMattsu** [comment]
@yanac 前のメモ、個人的にバーゴのやつおすすめだけど高い。アマゾンの安いやつでも問題はないと思う

**Comment by yanac** [comment]
2200円ならまっつんのオススメの方買うかな

**Comment by yanac** [comment]
バーゴの購入した！
