### ISSUE TITLE
第3回 コベリン登山部 〜川苔山〜

### ISSUE THREAD

**Issue by yanac** [covelline/mountain#6]
# 概要

基本的な方針として持ち物等は各個人で完結するような方針

## やること

- [x] リーダーを決める @yanac
- [x] リーダーがYAMAPで山行計画を立てる
   - ポイント
      - 温泉が駅の近くにあるとうれしい
      - 水場はあるか
      - 経験的にお昼の時間は1時間30分だった
      - 電車を利用する場合は電車の時間、バスを利用する場合はバスの時間
      - また念の為タクシーの電話番号も控えておく
- [x] 山行計画のざっくりなやつをGoogleカレンダーに入れる(コベリンの人が見れるようにしておく、[例はこんな感じ](https://user-images.githubusercontent.com/3356758/56298035-6e83bb80-616c-11e9-9163-532916f378f1.png))
   - バスの時間とかをピックアップしておくとみやすくていいかも
   - タクシーの連絡先も
- [x] リーダーがチェックリストを今回の山行に合わせたものにする
- [x] リーダーが登る山の天気を調べる
- [x] リーダーが前日に決行可否を通知する
- [x] リーダーが登山計画書を提出する
- [x] 親(身内)に山行計画を伝える
  - [x] 連絡がなかった場合に警察に連絡して貰えるようにする
- [x] 前日の20時くらいにチェックリストの確認をする、チェックしたら :+1: をつける
- [x] [ここ](https://covelline.staging.facilio.team/documents/new?body=%23%20%e7%ac%acX%e5%9b%9e%20%e3%82%b3%e3%83%99%e3%83%aa%e3%83%b3%e7%99%bb%e5%b1%b1%e9%83%a8%20XX%e5%b1%b1%20%e6%8c%af%e3%82%8a%e8%bf%94%e3%82%8a%0d%0a%23%23%20%e6%8c%af%e3%82%8a%e8%bf%94%e3%82%8a%0d%0a%0d%0a%e7%9b%ae%e7%9a%84%3a%e3%82%88%e3%81%8b%e3%81%a3%e3%81%9f%e3%81%93%e3%81%a8%e3%80%81%e6%94%b9%e5%96%84%e3%81%97%e3%81%9f%e3%81%bb%e3%81%86%e3%81%8c%e3%81%84%e3%81%84%e3%81%93%e3%81%a8%e3%82%92%e6%ac%a1%e5%9b%9e%e3%81%ae%e7%94%a8%e6%84%8f%e3%82%84%e5%b1%b1%e8%a1%8c%e3%81%ab%e6%b4%bb%e3%81%8b%e3%81%99%0d%0a%0d%0a%60%e3%81%93%e3%81%93%e3%81%abissue%e3%82%92%e8%b2%bc%e3%82%8b%60%0d%0a%0d%0a%23%23%23%20%40%e5%90%8d%e5%89%8d%0d%0a%0d%0a%23%23%23%23%20%e3%82%88%e3%81%8b%e3%81%a3%e3%81%9f%e3%81%93%e3%81%a8%0d%0a%0d%0a%23%23%23%23%20%e6%94%b9%e5%96%84%e3%81%97%e3%81%9f%e3%81%bb%e3%81%86%e3%81%8c%e3%81%84%e3%81%84%e3%81%93%e3%81%a8%0d%0a%0d%0a%23%23%23%20%40%e5%90%8d%e5%89%8d%20%0d%0a%0d%0a%23%23%23%23%20%e3%82%88%e3%81%8b%e3%81%a3%e3%81%9f%e3%81%93%e3%81%a8%0d%0a%0d%0a%23%23%23%23%20%e6%94%b9%e5%96%84%e3%81%97%e3%81%9f%e3%81%bb%e3%81%86%e3%81%8c%e3%81%84%e3%81%84%e3%81%93%e3%81%a8%0d%0a%0d%0a%23%23%23%20%e3%81%be%e3%81%a8%e3%82%81%e3%83%bbTry%0d%0a)をクリックして振り返りをする

## チェックリストテンプレート

```
# @名前

## 事前準備

- YAMAP用意
   - [ ] インストールする
   - [ ] メンバーと友達になる
   - [ ] 緊急連絡先等を事前に入力しておく
- [ ] 前日に爪を切る
- [ ] 登山日の山岳保険に入る
- [ ] 親(身内)に山行計画を伝える
  - [ ] 連絡がなかった場合に警察に連絡して貰えるようにする

## 必携品

- [ ] レインウェア
- [ ] ポイズンリムーバー
- [ ] 日焼け止め
- [ ] [エマージェンシーシート類](https://www.amazon.co.jp/%E3%83%8F%E3%82%A4%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88-HIGHMOUNT-%E3%82%B5%E3%83%90%E3%82%A4%E3%83%90%E3%83%AB%E3%82%B7%E3%83%BC%E3%83%88-%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%89-22134/dp/B000AR1HAU/)
- [ ] 健康保険証(コピー)
- [ ] クッカー
- [ ] 箸・スプーン等
- [ ] ストーブ類(ガスストーブ・アルコールストーブ・固形燃料等)
- [ ] [バーナーシート類](https://www.amazon.co.jp/UNIFLAME-%E3%83%A6%E3%83%8B%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0-%E3%83%90%E3%83%BC%E3%83%8A%E3%83%BC%E3%82%B7%E3%83%BC%E3%83%88-%E3%80%94%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%97%E7%94%A8%E5%93%81-%EF%BC%9A610596/dp/B07C2SN7Z7)
- [ ] ライター・マッチ
- [ ] ヘッドランプ
- [ ] ティッシュペーパー・紙タオル
- [ ] ウェットティッシュ
- 薬類
   - [ ] 絆創膏
   - [ ] 頭痛薬
   - [ ] 風邪薬
   - [ ] 正露丸
   - [ ] ガーゼ
- [ ] モバイルバッテリー
- [ ] 行動食
- [ ] 飲み水(750ml以上)
- [ ] 非常食(行動食とは別にカロリーメイト的なやつを)
- [ ] 携帯トイレ
- [ ] ジップロック(ゴミ用)
- [ ] 熊よけの鈴
- [ ] 手袋

## その他持っていくもの

ここは山行によって変わるので適宜、話あって変えること。

- [ ] 昼飯
- [ ] 昼飯で使う水
- [ ] お風呂セット(タオル・バスタオル)
- [ ] 着替え

```

**Comment by yanac** [comment]
https://tenkura.n-kishou.co.jp/tk/kanko/kad.html?code=13150010&type=15&ba=kk
今の所天気は大丈夫そう
![image](https://user-images.githubusercontent.com/2427741/58617379-efe97480-82fa-11e9-9da2-fef997f392d5.png)

**Comment by yanac** [comment]
川乗橋→奥多摩駅のバス時刻表
![image](https://user-images.githubusercontent.com/2427741/58617444-15767e00-82fb-11e9-8037-201c15d7e3e1.png)

**Comment by TakkuMattsu** [comment]
@yanac チェックリストは上に書いてあるやつでfixかな？

**Comment by yanac** [comment]
@TakkuMattsu 今回のチェックリストは上に書いてあるやつで行こうと思います！

**Comment by TakkuMattsu** [comment]
@yanac 了解！あとすげぇ細かいけどさっき追加したチェックリスト項目出来たらチェックリストテンプレートの中がいいかな！
追記してもらったのはリーダーのやることリストかも！

**Comment by yanac** [comment]
@TakkuMattsu ごめん！振り返り会でペア修正するのかと思ってテンプレートいじってない！

**Comment by TakkuMattsu** [comment]
@yanac あ、ここじゃなくて
![image](https://user-images.githubusercontent.com/3356758/58880175-44815b00-8712-11e9-9b2d-394e46683b4d.png)

こっちの中に入れたほうがいいかなと😅 
![image](https://user-images.githubusercontent.com/3356758/58880194-5400a400-8712-11e9-895c-09aca45ad9f8.png)

**Comment by yanac** [comment]
@TakkuMattsu あああああ！理解した！気づかなくてごめん！ｗ

**Comment by yanac** [comment]
# @yanac

## 事前準備

- YAMAP用意
   - [ ] インストールする
   - [ ] メンバーと友達になる
   - [ ] 緊急連絡先等を事前に入力しておく
- [ ] 前日に爪を切る
- [ ] 登山日の山岳保険に入る
- [ ] 親(身内)に山行計画を伝える
  - [ ] 連絡がなかった場合に警察に連絡して貰えるようにする

## 必携品

- [ ] レインウェア
- [ ] ポイズンリムーバー
- [ ] 日焼け止め
- [ ] [エマージェンシーシート類](https://www.amazon.co.jp/%E3%83%8F%E3%82%A4%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88-HIGHMOUNT-%E3%82%B5%E3%83%90%E3%82%A4%E3%83%90%E3%83%AB%E3%82%B7%E3%83%BC%E3%83%88-%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%89-22134/dp/B000AR1HAU/)
- [ ] 健康保険証(コピー)
- [ ] クッカー
- [ ] 箸・スプーン等
- [ ] ストーブ類(ガスストーブ・アルコールストーブ・固形燃料等)
- [ ] [バーナーシート類](https://www.amazon.co.jp/UNIFLAME-%E3%83%A6%E3%83%8B%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0-%E3%83%90%E3%83%BC%E3%83%8A%E3%83%BC%E3%82%B7%E3%83%BC%E3%83%88-%E3%80%94%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%97%E7%94%A8%E5%93%81-%EF%BC%9A610596/dp/B07C2SN7Z7)
- [ ] ライター・マッチ
- [ ] ヘッドランプ
- [ ] ティッシュペーパー・紙タオル
- [ ] ウェットティッシュ
- 薬類
   - [ ] 絆創膏
   - [ ] 頭痛薬
   - [ ] 風邪薬
   - [ ] 正露丸
   - [ ] ガーゼ
- [ ] モバイルバッテリー
- [ ] 行動食
- [ ] 飲み水(750ml以上)
- [ ] 非常食(行動食とは別にカロリーメイト的なやつを)
- [ ] 携帯トイレ
- [ ] ジップロック(ゴミ用)
- [ ] 熊よけの鈴
- [ ] 手袋

## その他持っていくもの

ここは山行によって変わるので適宜、話あって変えること。

- [ ] 昼飯
- [ ] 昼飯で使う水
- [ ] お風呂セット(タオル・バスタオル)
- [ ] 着替え

**Comment by TakkuMattsu** [comment]
# @TakkuMattsu 

## 事前準備

- YAMAP用意
   - [ ] インストールする
   - [ ] メンバーと友達になる
   - [ ] 緊急連絡先等を事前に入力しておく
- [ ] 前日に爪を切る
- [ ] 登山日の山岳保険に入る
- [ ] 親(身内)に山行計画を伝える
  - [ ] 連絡がなかった場合に警察に連絡して貰えるようにする

## 必携品

- [ ] レインウェア
- [ ] ポイズンリムーバー
- [ ] 日焼け止め
- [ ] [エマージェンシーシート類](https://www.amazon.co.jp/%E3%83%8F%E3%82%A4%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88-HIGHMOUNT-%E3%82%B5%E3%83%90%E3%82%A4%E3%83%90%E3%83%AB%E3%82%B7%E3%83%BC%E3%83%88-%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%89-22134/dp/B000AR1HAU/)
- [ ] 健康保険証(コピー)
- [ ] クッカー
- [ ] 箸・スプーン等
- [ ] ストーブ類(ガスストーブ・アルコールストーブ・固形燃料等)
- [ ] [バーナーシート類](https://www.amazon.co.jp/UNIFLAME-%E3%83%A6%E3%83%8B%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0-%E3%83%90%E3%83%BC%E3%83%8A%E3%83%BC%E3%82%B7%E3%83%BC%E3%83%88-%E3%80%94%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%97%E7%94%A8%E5%93%81-%EF%BC%9A610596/dp/B07C2SN7Z7)
- [ ] ライター・マッチ
- [ ] ヘッドランプ
- [ ] ティッシュペーパー・紙タオル
- [ ] ウェットティッシュ
- 薬類
   - [ ] 絆創膏
   - [ ] 頭痛薬
   - [ ] 風邪薬
   - [ ] 正露丸
   - [ ] ガーゼ
- [ ] モバイルバッテリー
- [ ] 行動食
- [ ] 飲み水(750ml以上)
- [ ] 非常食(行動食とは別にカロリーメイト的なやつを)
- [ ] 携帯トイレ
- [ ] ジップロック(ゴミ用)
- [ ] 熊よけの鈴
- [ ] 手袋

## その他持っていくもの

ここは山行によって変わるので適宜、話あって変えること。

- [ ] 昼飯
- [ ] 昼飯で使う水
- [ ] お風呂セット(タオル・バスタオル)
- [ ] 着替え

**Comment by yanac** [comment]
山行計画書です
https://docs.google.com/spreadsheets/d/1DnjHNDdqvbItswXrsQvrKUkYWkOBVmiVRFB7LWuzX7A/edit?usp=sharing

**Comment by yanac** [comment]
飲み水は明日の朝入れます。

**Comment by TakkuMattsu** [comment]
@yanac 了解！チェックした！また明日！

**Comment by yanac** [comment]
また明日！先おやすみ！

**Comment by TakkuMattsu** [comment]
日焼け止めは明日買います

**Comment by ryohey** [comment]
日焼け止め以外チェックOK

**Comment by yanac** [comment]
振り返り完了したので close
https://covelline.staging.facilio.team/documents/416
