### ISSUE TITLE
第5回 コベリン登山部 〜武甲山〜　8/20(火)

### ISSUE THREAD

**Issue by yanac** [covelline/mountain#9]
# 概要

基本的な方針として持ち物等は各個人で完結するような方針

## やること

- [x] リーダーを決める @yanac
- [x] リーダーがYAMAPで山行計画を立てる
   - ポイント
      - 温泉が駅の近くにあるとうれしい
      - 水場はあるか
      - 経験的にお昼の時間は1時間30分だった
      - 電車を利用する場合は電車の時間、バスを利用する場合はバスの時間
      - また念の為タクシーの電話番号も控えておく
- [x] 山行計画のざっくりなやつをGoogleカレンダーに入れる(コベリンの人が見れるようにしておく、[例はこんな感じ](https://user-images.githubusercontent.com/3356758/56298035-6e83bb80-616c-11e9-9163-532916f378f1.png))
   - バスの時間とかをピックアップしておくとみやすくていいかも
   - タクシーの連絡先も
- [x] リーダーがチェックリストを今回の山行に合わせたものにする
- [x] リーダーが登る山の天気を調べる
- [x] リーダーが前日に決行可否を通知する
- [ ] リーダーが登山計画書を提出する
- [x] 前日の20時くらいにチェックリストの確認をする、チェックしたら :+1: をつける
- [ ] [ここ](https://covelline.staging.facilio.team/documents/new?body=%23%20%e7%ac%acX%e5%9b%9e%20%e3%82%b3%e3%83%99%e3%83%aa%e3%83%b3%e7%99%bb%e5%b1%b1%e9%83%a8%20XX%e5%b1%b1%20%e6%8c%af%e3%82%8a%e8%bf%94%e3%82%8a%0d%0a%23%23%20%e6%8c%af%e3%82%8a%e8%bf%94%e3%82%8a%0d%0a%0d%0a%e7%9b%ae%e7%9a%84%3a%e3%82%88%e3%81%8b%e3%81%a3%e3%81%9f%e3%81%93%e3%81%a8%e3%80%81%e6%94%b9%e5%96%84%e3%81%97%e3%81%9f%e3%81%bb%e3%81%86%e3%81%8c%e3%81%84%e3%81%84%e3%81%93%e3%81%a8%e3%82%92%e6%ac%a1%e5%9b%9e%e3%81%ae%e7%94%a8%e6%84%8f%e3%82%84%e5%b1%b1%e8%a1%8c%e3%81%ab%e6%b4%bb%e3%81%8b%e3%81%99%0d%0a%0d%0a%60%e3%81%93%e3%81%93%e3%81%abissue%e3%82%92%e8%b2%bc%e3%82%8b%60%0d%0a%0d%0a%23%23%23%20%40%e5%90%8d%e5%89%8d%0d%0a%0d%0a%23%23%23%23%20%e3%82%88%e3%81%8b%e3%81%a3%e3%81%9f%e3%81%93%e3%81%a8%0d%0a%0d%0a%23%23%23%23%20%e6%94%b9%e5%96%84%e3%81%97%e3%81%9f%e3%81%bb%e3%81%86%e3%81%8c%e3%81%84%e3%81%84%e3%81%93%e3%81%a8%0d%0a%0d%0a%23%23%23%20%40%e5%90%8d%e5%89%8d%20%0d%0a%0d%0a%23%23%23%23%20%e3%82%88%e3%81%8b%e3%81%a3%e3%81%9f%e3%81%93%e3%81%a8%0d%0a%0d%0a%23%23%23%23%20%e6%94%b9%e5%96%84%e3%81%97%e3%81%9f%e3%81%bb%e3%81%86%e3%81%8c%e3%81%84%e3%81%84%e3%81%93%e3%81%a8%0d%0a%0d%0a%23%23%23%20%e3%81%be%e3%81%a8%e3%82%81%e3%83%bbTry%0d%0a)をクリックして振り返りをする

## チェックリストテンプレート

```
# @名前

## 事前準備

- YAMAP用意
   - [ ] インストールする
   - [ ] メンバーと友達になる
   - [ ] 緊急連絡先等を事前に入力しておく
- [ ] 前日に爪を切る
- [ ] 登山日の山岳保険に入る
- [ ] 親(身内)に山行計画を伝える
  - 連絡がなかった場合に警察に連絡して貰えるようにする

## 必携品

- [ ] レインウェア
- [ ] ポイズンリムーバー
- [ ] 日焼け止め
- [ ] [エマージェンシーシート類](https://www.amazon.co.jp/%E3%83%8F%E3%82%A4%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88-HIGHMOUNT-%E3%82%B5%E3%83%90%E3%82%A4%E3%83%90%E3%83%AB%E3%82%B7%E3%83%BC%E3%83%88-%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%89-22134/dp/B000AR1HAU/)
- [ ] 健康保険証(コピー)
- [ ] クッカー
- [ ] 箸・スプーン等
- [ ] ストーブ類(ガスストーブ・アルコールストーブ・固形燃料等)
- [ ] [バーナーシート類](https://www.amazon.co.jp/UNIFLAME-%E3%83%A6%E3%83%8B%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0-%E3%83%90%E3%83%BC%E3%83%8A%E3%83%BC%E3%82%B7%E3%83%BC%E3%83%88-%E3%80%94%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%97%E7%94%A8%E5%93%81-%EF%BC%9A610596/dp/B07C2SN7Z7)
- [ ] ライター・マッチ
- [ ] ヘッドランプ
- [ ] ティッシュペーパー・紙タオル
- [ ] ウェットティッシュ
- 薬類
   - [ ] 絆創膏
   - [ ] 頭痛薬
   - [ ] 風邪薬
   - [ ] 正露丸
   - [ ] ガーゼ
- [ ] モバイルバッテリー
- [ ] 行動食
- [ ] 飲み水(25℃以上は2.0ℓ以上、それ以外は1.5ℓ)
- [ ] 非常食(行動食とは別にカロリーメイト的なやつを)
- [ ] 携帯トイレ
- [ ] ジップロック(ゴミ用)
- [ ] 熊よけの鈴
- [ ] 手袋

## その他持っていくもの

ここは山行によって変わるので適宜、話あって変えること。

- [ ] 昼飯
- [ ] お風呂セット(タオル・バスタオル)
- [ ] 着替え

```

**Comment by yanac** [comment]
山行計画表
https://docs.google.com/spreadsheets/d/19xHi40tiYHR53UoK8HlC661Lo2gV15HC7xhA5ja4VLk/edit?usp=sharing

**Comment by yanac** [comment]
ポイント | P到着時刻 | 休憩(時) | 休憩(分) | P出発時刻 | 時 | 分 | 備考
-- | -- | -- | -- | -- | -- | -- | --
浦山口駅 | 8:05 |   | 10 | 8:15 | 0 | 10 |  
P2 | 8:25 |   | 0 | 8:25 | 1 | 0 |  
P3 | 9:25 |   | 10 | 9:35 | 0 | 55 | 次めっちゃキツイ登りがあるので休憩有り
P4 | 10:30 |   | 0 | 10:30 | 0 | 40 |  
P5 | 11:10 |   | 10 | 11:20 | 1 | 0 |  
P6 | 12:20 |   | 0 | 12:20 | 0 | 10 |  
山頂 | 12:30 | 1 | 30 | 14:00 | 0 | 30 | 山頂でご飯
P8 | 14:30 |   | 0 | 14:30 | 0 | 35 |  
P9 | 15:05 |   | 10 | 15:15 | 0 | 5 |  
P10 | 15:20 |   | 0 | 15:20 | 0 | 10 |  
P11 | 15:30 |   | 10 | 15:40 | 0 | 15 |  
P12 | 15:55 |   | 0 | 15:55 | 1 | 0 |  
P13 | 16:55 |   | 0 | 16:55 | 0 | 15 |  
横瀬駅 | 17:10 |   |   |   |   |   |

**Comment by yanac** [comment]
https://yamap.com/plans/code/Ve8R1RSwbeS6wZIXOQBtiAbKoemsp4fQGjaVx-9_EIJAijpEWb5wGhKERCMTPcKKcFY

**Comment by yanac** [comment]
電車(始発の次)

![image](https://user-images.githubusercontent.com/2427741/62935374-eb186500-be01-11e9-974b-211a93d12f4c.png)

**Comment by yanac** [comment]
@TakkuMattsu まっつんオフィス泊まる前提の計画になっちゃった

**Comment by yanac** [comment]
まっつんオフィス泊まらないで出発だと山行計画が全部1時間後ろにズレるわ

![image](https://user-images.githubusercontent.com/2427741/62935496-4185a380-be02-11e9-89f1-ba7d47a8ea39.png)

**Comment by yanac** [comment]
@TakkuMattsu まっつんオフィス泊まらないで出発だと山行計画が全部1時間後ろにズレるんだけど、
登山道入り口から駅までの道が17:00~18:00だから暗くなっても大丈夫だと思うけど大丈夫かな？

桜上水からいくプランと池袋オフィス一泊でいくプランどっちが良いか明日話そう

**Comment by yanac** [comment]
温泉
http://www.buko-onsen.co.jp/kanko/
![image](https://user-images.githubusercontent.com/2427741/62935717-cf618e80-be02-11e9-85dc-7a202bc023b4.png)

**Comment by TakkuMattsu** [comment]
@yanac オフィス泊まるー！

**Comment by TakkuMattsu** [comment]
# @TakkuMattsu 

## 事前準備

- YAMAP用意
   - [ ] インストールする
   - [ ] メンバーと友達になる
   - [ ] 緊急連絡先等を事前に入力しておく
- [ ] 前日に爪を切る
- [ ] 登山日の山岳保険に入る
- [ ] 親(身内)に山行計画を伝える
  - 連絡がなかった場合に警察に連絡して貰えるようにする

## 必携品

- [ ] レインウェア
- [ ] ポイズンリムーバー
- [ ] 日焼け止め
- [ ] [エマージェンシーシート類](https://www.amazon.co.jp/%E3%83%8F%E3%82%A4%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88-HIGHMOUNT-%E3%82%B5%E3%83%90%E3%82%A4%E3%83%90%E3%83%AB%E3%82%B7%E3%83%BC%E3%83%88-%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%89-22134/dp/B000AR1HAU/)
- [ ] 健康保険証(コピー)
- [ ] クッカー
- [ ] 箸・スプーン等
- [ ] ストーブ類(ガスストーブ・アルコールストーブ・固形燃料等)
- [ ] [バーナーシート類](https://www.amazon.co.jp/UNIFLAME-%E3%83%A6%E3%83%8B%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0-%E3%83%90%E3%83%BC%E3%83%8A%E3%83%BC%E3%82%B7%E3%83%BC%E3%83%88-%E3%80%94%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%97%E7%94%A8%E5%93%81-%EF%BC%9A610596/dp/B07C2SN7Z7)
- [ ] ライター・マッチ
- [ ] ヘッドランプ
- [ ] ティッシュペーパー・紙タオル
- [ ] ウェットティッシュ
- 薬類
   - [ ] 絆創膏
   - [ ] 頭痛薬
   - [ ] 風邪薬
   - [ ] 正露丸
   - [ ] ガーゼ
- [ ] モバイルバッテリー
- [ ] 行動食
- [ ] 飲み水(25℃以上は2.0ℓ以上、それ以外は1.5ℓ)
- [ ] 非常食(行動食とは別にカロリーメイト的なやつを)
- [ ] 携帯トイレ
- [ ] ジップロック(ゴミ用)
- [ ] 熊よけの鈴
- [ ] 手袋

## その他持っていくもの

ここは山行によって変わるので適宜、話あって変えること。

- [ ] 昼飯
- [ ] お風呂セット(タオル・バスタオル)
- [ ] 着替え

**Comment by yanac** [comment]
# @yanac

## 事前準備

- YAMAP用意
   - [ ] インストールする
   - [ ] メンバーと友達になる
   - [ ] 緊急連絡先等を事前に入力しておく
- [ ] 前日に爪を切る
- [ ] 登山日の山岳保険に入る
- [ ] 親(身内)に山行計画を伝える
  - 連絡がなかった場合に警察に連絡して貰えるようにする

## 必携品

- [ ] レインウェア
- [ ] ポイズンリムーバー
- [ ] 日焼け止め
- [ ] [エマージェンシーシート類](https://www.amazon.co.jp/%E3%83%8F%E3%82%A4%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%88-HIGHMOUNT-%E3%82%B5%E3%83%90%E3%82%A4%E3%83%90%E3%83%AB%E3%82%B7%E3%83%BC%E3%83%88-%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%89-22134/dp/B000AR1HAU/)
- [ ] 健康保険証(コピー)
- [ ] クッカー
- [ ] 箸・スプーン等
- [ ] ストーブ類(ガスストーブ・アルコールストーブ・固形燃料等)
- [ ] [バーナーシート類](https://www.amazon.co.jp/UNIFLAME-%E3%83%A6%E3%83%8B%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0-%E3%83%90%E3%83%BC%E3%83%8A%E3%83%BC%E3%82%B7%E3%83%BC%E3%83%88-%E3%80%94%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%97%E7%94%A8%E5%93%81-%EF%BC%9A610596/dp/B07C2SN7Z7)
- [ ] ライター・マッチ
- [ ] ヘッドランプ
- [ ] ティッシュペーパー・紙タオル
- [ ] ウェットティッシュ
- 薬類
   - [ ] 絆創膏
   - [ ] 頭痛薬
   - [ ] 風邪薬
   - [ ] 正露丸
   - [ ] ガーゼ
- [ ] モバイルバッテリー
- [ ] 行動食
- [ ] 飲み水(25℃以上は2.0ℓ以上、それ以外は1.5ℓ)
- [ ] 非常食(行動食とは別にカロリーメイト的なやつを)
- [ ] 携帯トイレ
- [ ] ジップロック(ゴミ用)
- [ ] 熊よけの鈴
- [ ] 手袋

## その他持っていくもの

ここは山行によって変わるので適宜、話あって変えること。

- [ ] 昼飯
- [ ] お風呂セット(タオル・バスタオル)
- [ ] 着替え

**Comment by yanac** [comment]
https://tenkura.n-kishou.co.jp/tk/kanko/kad.html?code=11150003&type=15&ba=kk
![image](https://user-images.githubusercontent.com/2427741/63271138-6f705980-c2d4-11e9-80e5-b223b53b2fa6.png)

**Comment by yanac** [comment]
現状の予報だと天気は大丈夫そう。近隣の街は雨の模様。

**Comment by yanac** [comment]
@TakkuMattsu 振り返り忘れていた気がする。いつやる？

**Comment by TakkuMattsu** [comment]
@yanac 今日の18:50からで！それまでに書きます！

**Comment by TakkuMattsu** [comment]
今回の振り返り
https://covelline.staging.facilio.team/documents/490/edit
